---
- name: Criar usuário e gerenciar permissões # Configuração de exemplo, nome do playbook
  hosts: targets
  become: true

  tasks:
    - name: Criar usuário devops com senha e bash # Cria um usuário chamado 'devops' com a senha especificada
      user:
        name: devops
        password: "{{ 'Devops123!@#' | password_hash('sha512') }}"
        shell: /bin/bash
        groups: sudo,docker
        append: yes
        state: present

    - name: Criar diretório de aplicação # Cria o diretório /opt/app com permissões apropriadas
      file:
        path: /opt/app
        state: directory
        owner: devops
        group: devops
        mode: '0755'

    - name: Criar diretório de logs # Cria o diretório /opt/logs com permissões apropriadas
      file:
        path: /opt/logs
        state: directory
        owner: devops
        group: devops
        mode: '0755'

    - name: Criar arquivo de teste no diretório de app # Cria um arquivo de status.txt para verificar permissões
      copy:
        content: "Aplicação iniciada em {{ ansible_date_time.date }} {{ ansible_date_time.time }}\n"
        dest: /opt/app/status.txt
        owner: devops
        group: devops
        mode: '0644'

    - name: Criar arquivo de log simulado # Cria um arquivo de log inicial no diretório de logs
      shell: echo "log iniciado em $(date)" > /opt/logs/inicial.log